name: Update JSON Price Files
on:
  schedule:
    - cron: '0 0 * * *'  # At 00:00
  workflow_dispatch:  # allow manual trigger
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Update JSON file
        run: |
          echo '{"updated": "'$(date -u +'%Y-%m-%d %H:%M:%S UTC')'"}'
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          yarn install
          yarn global add tsx
          tsx src/save-json-github.ts
